config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  resources :subjects
  resources :teachers
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#home"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
    belongs_to :teacher
    belongs_to :subject
    belongs_to :user
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_evaluation, only: %i[ show edit update destroy ]

  # GET /evaluations or /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1 or /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
    @profs = Teacher.all
    @subs = Subject.all
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations or /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)
    @evaluation.user = current_user
    respond_to do |format|
      if @evaluation.save!
        TeachersController.new.update_prof_score(@evaluation.teacher)
        format.html { redirect_to teacher_url(@evaluation.teacher), notice: "Avaliação criada com sucesso!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1 or /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to evaluation_url(@evaluation), notice: "Evaluation was successfully updated." }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1 or /evaluations/1.json
  def destroy
    @evaluation.destroy

    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: "Evaluation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evaluation_params
      params.require(:evaluation).permit(
        :teacher_id,
        :subject_id,
        :overallGrade,
        :usedTime,
        :externalThings,
        :goodKnoledge,
        :takeAgain,
        :attendenceDemand
      )
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_evaluation.html.erb
<div id="<%= dom_id evaluation %>">
</div>

app/views/evaluations/_form.html.erb
<%= simple_form_for @evaluation do |f| %>
  <div class="row">
    <div class="col-md-6 mb-5">
      <label class="label-items">Qual professor deseja avaliar?</label>
      <%= f.collection_select :teacher_id, Teacher.order(:name), :id, :name, { prompt: "Escolha o Professor" }, { style: 'width: 90% !important;' } %>
    </div>
    <div class="col-md-6 mb-5">
      <label class="label-items">Qual disciplina o professor lecionou?</label>
      <%= f.collection_select :subject_id, Subject.order(:name), :id, :name, { prompt: "Escolha a disciplina" }, { style: 'width: 90% !important;' } %>
    </div>
  </div>
    
  <div class="row">
    <div class="col-12 mb-5">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Nota geral:</label>
        <small class="subtitle">Essa é a nota que você acha que o professor merece. Levando em consideração todos os aspectos julgados pelo aluno.</small>
      </div>
      <%= f.input :overallGrade, as: :range, label: false, input_html:{ min:"0", max:"10", class: 'w-100'} %>
      <div class='d-flex justify-content-between descricao-range'>
        <span>0</span>
        <span>10</span>
      </div>
    </div>
  </div>

  <div class="col-12">
    <div class="rating-container">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Conhecimento</label>
        <small class="subtitle">Você diria que o professor apresentou dominio da matéria lecionada?</small>
      </div>
      <div class="">
        <div class="rating">
            <label for="super-sad3">
              <%= f.radio_button :goodKnoledge, false, class: 'super-sad', id: 'super-sad3' %>
              <svg viewBox="0 0 24 24"><path d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
            </label>
            <label for="super-happy3">
              <%= f.radio_button :goodKnoledge, true, class: 'super-happy', id: 'super-happy3' %>
              <svg viewBox="0 0 24 24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
            </label>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12">
    <div class="rating-container">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Aproveitamento do tempo</label>
        <small class="subtitle">Você diria que o tempo disponível dentro de sala de aula foi bem aproveitado pelo professor?</small>
      </div>
      <div class="">
        <div class="rating">
            <label for="super-sad1">
              <%= f.radio_button :usedTime, false, class: 'super-sad', id: 'super-sad1' %>
              <svg viewBox="0 0 24 24"><path d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
            </label>
            <label for="super-happy1">
              <%= f.radio_button :usedTime, true, class: 'super-happy', id: 'super-happy1' %>
              <svg viewBox="0 0 24 24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
            </label>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12">
    <div class="rating-container">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Compreensão</label>
        <small class="subtitle">Você diria que o professor foi compreensivo com relação a questões externas a sala de aula?</small>
      </div>
      <div class="">
        <div class="rating">
            <label for="super-sad2">
              <%= f.radio_button :externalThings, false, class: 'super-sad', id: 'super-sad2' %>
              <svg viewBox="0 0 24 24"><path d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
            </label>
            <label for="super-happy2">
              <%= f.radio_button :externalThings, true, class: 'super-happy', id: 'super-happy2' %>
              <svg viewBox="0 0 24 24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
            </label>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12">
    <div class="rating-container">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Presença</label>
        <small class="subtitle">Esse professor reprovou algum aluno por falta na disciplina?</small>
      </div>
      <div class="">
        <div class="rating">
            <label for="super-sad5">
              <%= f.radio_button :attendenceDemand, false, class: 'super-sad', id: 'super-sad5' %>
              <svg viewBox="0 0 24 24"><path d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
            </label>
            <label for="super-happy5">
              <%= f.radio_button :attendenceDemand, true, class: 'super-happy', id: 'super-happy5' %>
              <svg viewBox="0 0 24 24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
            </label>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12">
    <div class="rating-container">
      <div class="d-flex flex-column mb-3">
        <label class="label-items">Indicação</label>
        <small class="subtitle">Você indicaria fazer essa disciplina com essse professor para um colega?</small>
      </div>
      <div class="">
        <div class="rating">
            <label for="super-sad4">
              <%= f.radio_button :takeAgain, false, class: 'super-sad', id: 'super-sad4' %>
              <svg viewBox="0 0 24 24"><path d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
            </label>
            <label for="super-happy4">
                <%= f.radio_button :takeAgain, true, class: 'super-happy', id: 'super-happy4' %>
              <svg viewBox="0 0 24 24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
            </label>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12 d-flex justify-content-center">
    <%= f.button :submit, 'Enviar avaliação', class: 'btn btn-primary mt-5' %>
  </div>
<% end %>

<script>
  $(document).ready(function() { 
    $('#evaluation_teacher_id').select2().val('<%= session[:avalProv] if session[:avalProv] %>').trigger('change');
    $('#evaluation_subject_id').select2().val('<%= session[:avalSub] if session[:avalSub] %>').trigger('change');
    $("#evaluation_overallGrade").slider({ min: 0, max: 10 });
  });
</script>

app/views/evaluations/edit.html.erb
<h1>Editing evaluation</h1>

<%= render "form", evaluation: @evaluation %>

<br>

<div>
  <%= link_to "Show this evaluation", @evaluation %> |
  <%= link_to "Back to evaluations", evaluations_path %>
</div>

app/views/evaluations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluations</h1>

<div id="evaluations">
  <% @evaluations.each do |evaluation| %>
    <%= render evaluation %>
    <p>
      <%= link_to "Show this evaluation", evaluation %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluation", new_evaluation_path %>

app/views/evaluations/new.html.erb
<main id="main">
  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <%= link_to root_path do %>
              <i class="fa-solid fa-arrow-left p-2 text-dark" data-toggle="tooltip" data-placement="top" title="Votar"></i>
          <% end %>
          <h2>Avaliação</h2>
        </div>
        <ol>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Avaliação', new_evaluation_path %></li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs Section -->

  <section class="inner-page">
    <div class="container inner-form">
      <%= render "form" %>
    </div>
  </section>

</main>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>  

app/views/evaluations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluation %>

<div>
  <%= link_to "Edit this evaluation", edit_evaluation_path(@evaluation) %> |
  <%= link_to "Back to evaluations", evaluations_path %>

  <%= button_to "Destroy this evaluation", @evaluation, method: :delete %>
</div>