config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  resources :subjects
  resources :teachers
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#home"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/shared/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row d-flex justify-content-around">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>UNIRIO</h3>
            <p>
              Avenida Pasteur, 458 <br>
              Rio de Janeiro, RJ 22290-255<br>
              Brasil <br><br>
              <strong>Telefone:</strong> +55 21 3873-6400<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Links Úteis</h4>
            <ul>
              <li><i class="fa-solid fa-chevron-right"></i> <%= link_to 'Professores do curso', teachers_path %></li>
              <li><i class="fa-solid fa-chevron-right"></i> <%= link_to 'Disciplinas oferecidas', subjects_path %></li>
              <% if user_signed_in? %>
                <li><i class="fa-solid fa-chevron-right"></i> <%= link_to 'Avaliar um docente', new_evaluation_path %></li>
                <li><i class="fa-solid fa-chevron-right"></i> <%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>   
              <% end %>
            </ul>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Lucas Diniz Cunha</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by <%= link_to 'Lucas Diniz Cunha', 'https://www.linkedin.com/in/lucasdinizcunha/', target: "_blank" %>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <%= link_to 'https://www.unirio.br/', target: "_blank" do %>
            <i class="fa-solid fa-building-columns"></i>
        <% end %>
        <%= link_to 'https://bsi.uniriotec.br/', target: "_blank" do %>
            <i class="fa-solid fa-graduation-cap"></i>
        <% end %>
        <%= link_to 'https://www.facebook.com/lucas.dinizcunha/', target: "_blank" do %>
            <i class="fa-brands fa-square-facebook"></i>
        <% end %>
        <%= link_to 'https://www.instagram.com/lucasdiniz47/', target: "_blank" do %>
            <i class="fa-brands fa-square-instagram"></i>
        <% end %>
        <%= link_to 'https://www.linkedin.com/in/lucasdinizcunha/', target: "_blank" do %>
            <i class="fa-brands fa-linkedin"></i>
        <% end %>
      </div>
    </div>
    
  </footer><!-- End Footer -->

app/views/shared/_navbar.html.erb
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex justify-content-between align-items-center">

        <%= link_to root_path, class: "" do %>
            <h1 class="logo me-auto">Profscore</h1>
        <% end %>

        <div class='d-flex align-items-center'>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><%= link_to 'Home', root_path, class: "nav-link scrollto #{'active' if current_page?(root_path)}" %></li>
                    <li><%= link_to 'Professores', teachers_path, class: "nav-link scrollto #{'active' if current_page?(teachers_path)}" %></li>
                    <li><%= link_to 'Disciplinas', subjects_path, class: "nav-link scrollto #{'active' if current_page?(subjects_path)}" %></li>
                </ul>
            </nav>
            
            <div>
                <% if user_signed_in? %>
                    <div class='d-flex'>
                        <%= link_to new_evaluation_path, class: "appointment-btn scrollto" do %>
                            Avaliar
                        <% end %>
                        <div class="dropdown">
                            <i class="fa-solid fa-user profile-btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></i>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><%= link_to 'Deslogar', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                            </ul>
                        </div>
                    <div>
                <% else %>
                    <%= link_to new_user_session_path, class: "appointment-btn scrollto" do %>
                        Login
                    <% end %>
                <% end %>
            </div>
        </div>

    </div>
</header>
<!-- End Header -->

app/views/shared/_toastSucessoCopiaEmail.html.erb
<!-- Toast Modal -->
<div class="toast toast-copied bg-success" id="copiedToast">
  <div class="toast-header">
      <strong class="mr-auto">Sucesso!</strong>
  </div>
  <div class="toast-body text-white">
      O email foi copiado para sua área de transferência.
  </div>
</div>