config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  resources :subjects
  resources :teachers
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#home"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :evaluations
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
    @subjectsOldNMand = Subject.all.select { |sub| sub.code.include?('2008') && !sub.mandatory }
    @subjectsOldMand = Subject.all.select { |sub| sub.code.include?('2008') && sub.mandatory }
    @subjectsNewNMand = Subject.all.select { |sub| sub.code.include?('2023') && !sub.mandatory }
    @subjectsNewMand = Subject.all.select { |sub| sub.code.include?('2023') && sub.mandatory }
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.fetch(:subject, {})
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
</div>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<main id="main">
  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <span style='display: flex' class='align-items-center'>
          <%= link_to root_path, class: "color-secondary" do %>
              <i class="fa-solid fa-arrow-left"></i>
          <% end %>
          <h2 style='margin: 0 0 0 12px;'>Disciplinas</h2>
        </span>
        <ol>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Disciplinas', subjects_path %></li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs Section -->

  <section class="inner-page">
    <div class="container">
      <h5>Obrigatorias 2008 <span class='sub-count'><%= @subjectsOldMand.count %></h5>
      <div class="subjects-grid">
        <% @subjectsOldMand.each do |subject| %>
          <div class="card border-default">
            <div class="card-body"> 
              <h5 class="card-title"><%= subject.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= subject.code %></h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <section class="inner-page">
    <div class="container">
      <h5>Optativas 2008 <span class='sub-count'><%= @subjectsOldNMand.count %></h5>
      <div class="subjects-grid">
        <% @subjectsOldNMand.each do |subject| %>
          <div class="card border-default">
            <div class="card-body"> 
              <h5 class="card-title"><%= subject.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= subject.code %></h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <section class="inner-page">
    <div class="container">
      <h5>Obrigatorias 2023 <span class='sub-count'><%= @subjectsNewMand.count %></span></h5>
      <div class="subjects-grid">
        <% @subjectsNewMand.each do |subject| %>
          <div class="card border-default">
            <div class="card-body"> 
              <h5 class="card-title"><%= subject.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= subject.code %></h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <section class="inner-page">
    <div class="container">
      <h5>Optativas 2023 <span class='sub-count'><%= @subjectsNewNMand.count %></span></h5>
      <div class="subjects-grid">
        <% @subjectsNewNMand.each do |subject| %>
          <div class="card border-default">
            <div class="card-body"> 
              <h5 class="card-title"><%= subject.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= subject.code %></h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

  <section class="inner-page">
    <div class="container">
      <h5>Todas disciplinas <span class='sub-count'><%= @subjects.count %></span></h5>
      <div class="subjects-grid">
        <% @subjects.each do |subject| %>
          <div class="card border-default">
            <div class="card-body"> 
              <h5 class="card-title"><%= subject.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= subject.code %></h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

</main>

<%= render 'shared/toastSucessoCopiaEmail' %>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // copy email function
  function copyEmail(text) {
    navigator.clipboard.writeText(text);
    $('#copiedToast').toast('show');
    setTimeout(function () {
        $('#copiedToast').toast('hide');
    }, 2000);
  }
</script>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>

<div>
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>

  <%= button_to "Destroy this subject", @subject, method: :delete %>
</div>