config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  resources :subjects
  resources :teachers
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#home"

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :evaluations
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all.sort_by {|obj| obj.name}
  end

  # GET /teachers/1 or /teachers/1.json
  def show
    @totTrueExternalThings = @teacher.evaluations.where(externalThings: true).count
    @totTrueGoodKnoledge = @teacher.evaluations.where(goodKnoledge: true).count
    @totTrueTakeAgain = @teacher.evaluations.where(takeAgain: true).count
    @totTrueAttendenceDemand = @teacher.evaluations.where(attendenceDemand: true).count
    @totTrueUsedTime = @teacher.evaluations.where(usedTime: true).count
    @totEvaluations = @teacher.evaluations.count
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_prof_score(teacher)
    @teacher = teacher
    grade = 0.0
    count = 0
    @teacher.evaluations.each do |e|
        grade += e.overallGrade
        count += 1
    end
    @teacher.overallGrade = grade/count
    @teacher.overallGrade.round(2)
    @teacher.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.fetch(:teacher, {})
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
</div>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<main id="main">
  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <span style='display: flex' class='align-items-center'>
          <%= link_to root_path, class: "color-secondary" do %>
              <i class="fa-solid fa-arrow-left"></i>
          <% end %>
          <h2 style='margin: 0 0 0 12px;'>Professores</h2>
        </span>
        <ol>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Professores', teachers_path %></li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs Section -->

  <section class="inner-page">
    <div class="container">
      <div class="teachers-grid">
        <% @teachers.each do |teacher| %>
          <div class="card">
            <div class="card-body">
              <div class='d-flex justify-content-between'>
                
                <%= link_to teacher_path(teacher), class: 'card-title' do %>
                  <h5 class="card-title"><%= teacher.name %></h5>
                <% end %>
                <h5 class="card-title mx-2"><%= teacher.overallGrade %></h5>
              </div>
              <h6 class="card-subtitle mb-2 text-muted"><%= teacher.position %></h6>
              <%= link_to "#{ teacher.lattes }", target: "_blank" do %>
                  <i class="fa-solid fa-building-columns pt-2" data-toggle="tooltip" data-placement="top" title="Lattes"></i>
              <% end %>
              <span class="span-email color-default" onclick="copyEmail(<%= teacher.email.to_json %>)" data-toggle="tooltip" data-placement="top" title="Copiar email">
                  <i class="fa-regular fa-envelope"></i>
              </span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

</main>

<%= render 'shared/toastSucessoCopiaEmail' %>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  // copy email function
  function copyEmail(text) {
    navigator.clipboard.writeText(text);
    $('#copiedToast').toast('show');
    setTimeout(function () {
        $('#copiedToast').toast('hide');
    }, 2000);
  }
</script>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<main id="main">
  <!-- ======= Breadcrumbs Section ======= -->
  <section class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <%= link_to teachers_path do %>
              <i class="fa-solid fa-arrow-left p-2 text-dark" data-toggle="tooltip" data-placement="top" title="Votar"></i>
          <% end %>
          <h2><%= @teacher.name %></h2>
        </div>
        <ol>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Professores', teachers_path %></li>
          <li><%= link_to "#{@teacher.name}", teacher_path(@teacher) %></li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs Section -->

  <section class="inner-page">
    <div class="container">
      <div class='row'>
        <div class="col-lg-3 col-sm-12 d-flex flex-column align-items-end px-5 mb-3">
          <div class="d-flex">
            <span class='grade color-default mx-2'><%= @teacher.overallGrade %></span>
            <span class='color-secondary pt-4 mx-2'> / 10</span>
          </div>
          <small> Baseado em <%= @totEvaluations %> avaliações </small>
        </div>

        <div class="col-lg-8 col-sm-12 d-flex flex-column">
          <div class="card">
            <div class="card-body">
              <h3 class="text-center mb-5">Avaliação agregada dos alunos:</h3>
              <div class="d-flex justify-content-around mb-2">
                <P class="border-dark border-bottom">Conhecimento: <span class="color-default"><%= @totTrueGoodKnoledge %> / <%= @totEvaluations %></span></p>
                <p class="border-dark border-bottom">Tempo bem utilizado: <span class="color-default"><%= @totTrueUsedTime %> / <%= @totEvaluations %></span></p>
                <p class="border-dark border-bottom">Compreensivo: <span class="color-default"><%= @totTrueExternalThings %> / <%= @totEvaluations %></span></p>
              </div>
              <div class="d-flex justify-content-around">
                <p class="border-dark border-bottom">Reprova por falta: <span class="color-default"><%= @totTrueAttendenceDemand %> / <%= @totEvaluations %></span></p>
                <p class="border-dark border-bottom">Recomendaria: <span class="color-default"><%= @totTrueTakeAgain %> / <%= @totEvaluations %></span></p>
              </div>
            </div>
          </div>

        </div>
      </div>

      <p class="container m-5 p-5 mb-3 pb-1">Avaliações individuais</p>

      <% @teacher.evaluations.each do |eval| %>
        <div class="row d-flex justify-content-center">
          <div class="card my-4 col-9">
            <div class="card-body">
              <div class='d-flex justify-content-start'>
                <div class="col-lg-2">
                  <span class="overall-grade <%= eval.overallGrade >= 7 ? "bg-success" : eval.overallGrade <= 3 ? "bg-danger" : "bg-warning" %>"><%= eval.overallGrade %></span>
                </div>
                <div class="d-flex flex-column col-10">
                  <div class="row">
                    <span class="col-6"> Domina a materia: <span class="font-weight-bold"><%= eval.goodKnoledge ? "Sim" : "Não" %></span></span>
                    <span class="col-6"> Tempo bem utilizado: <span class="font-weight-bold"><%= eval.usedTime ? "Sim" : "Não" %></span></span>
                  </div>
                  <div class="row">
                    <span class="col-6"> Compreensivo: <span class="font-weight-bold"><%= eval.externalThings ? "Sim" : "Não" %></span></span>
                    <span class="col-6"> Reprova por falta: <span class="font-weight-bold"><%= eval.attendenceDemand ? "Sim" : "Não" %></span></span>
                  </div>
                  <div class="row">
                    <span class="col-6"> Recomendaria: <span class="font-weight-bold"><%= eval.takeAgain ? "Sim" : "Não" %></span></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>



    </div>
  </section>

</main>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>  